// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct InfiniteBountiesClientProgram;
impl sails_rs::client::Program for InfiniteBountiesClientProgram {}
pub trait InfiniteBountiesClient {
    type Env: sails_rs::client::GearEnv;
    fn bounty_board(&self) -> sails_rs::client::Service<bounty_board::BountyBoardImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> InfiniteBountiesClient
    for sails_rs::client::Actor<InfiniteBountiesClientProgram, E>
{
    type Env = E;
    fn bounty_board(&self) -> sails_rs::client::Service<bounty_board::BountyBoardImpl, Self::Env> {
        self.service(stringify!(BountyBoard))
    }
}
pub trait InfiniteBountiesClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(
        self,
        admin: ActorId,
        fee: u128,
    ) -> sails_rs::client::PendingCtor<InfiniteBountiesClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> InfiniteBountiesClientCtors
    for sails_rs::client::Deployment<InfiniteBountiesClientProgram, E>
{
    type Env = E;
    fn new(
        self,
        admin: ActorId,
        fee: u128,
    ) -> sails_rs::client::PendingCtor<InfiniteBountiesClientProgram, io::New, Self::Env> {
        self.pending_ctor((admin, fee))
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New (admin: ActorId, fee: u128) -> ());
}

pub mod bounty_board {
    use super::*;
    pub trait BountyBoard {
        type Env: sails_rs::client::GearEnv;
        /// Approve submitted work. Releases the reward to the claimant.
        fn approve_bounty(
            &mut self,
            bounty_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApproveBounty, Self::Env>;
        /// Cancel an open (unclaimed) bounty. Reward is returned to creator.
        fn cancel_bounty(
            &mut self,
            bounty_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelBounty, Self::Env>;
        /// Claim an open bounty. Caller becomes the claimant.
        fn claim_bounty(
            &mut self,
            bounty_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimBounty, Self::Env>;
        /// Import state from a previous program. Admin only.
        /// Overwrites ALL current state with the imported data.
        fn import_state(
            &mut self,
            encoded_state: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::ImportState, Self::Env>;
        /// Post a new bounty. Requires msg::value() >= fee + reward.
        /// fee is collected by the contract, reward is locked for the claimant.
        fn post_bounty(
            &mut self,
            description: String,
            metadata_url: String,
        ) -> sails_rs::client::PendingCall<io::PostBounty, Self::Env>;
        /// Set the service fee. Admin only.
        fn set_fee(
            &mut self,
            new_fee: u128,
        ) -> sails_rs::client::PendingCall<io::SetFee, Self::Env>;
        /// Submit proof of work for a claimed bounty.
        fn submit_work(
            &mut self,
            bounty_id: u64,
            proof_url: String,
        ) -> sails_rs::client::PendingCall<io::SubmitWork, Self::Env>;
        /// Withdraw accumulated fees to admin. Admin only.
        fn withdraw_fees(&mut self) -> sails_rs::client::PendingCall<io::WithdrawFees, Self::Env>;
        /// Export all state for migration to a new program. Admin only.
        fn export_state(&self) -> sails_rs::client::PendingCall<io::ExportState, Self::Env>;
        /// Get all bounties created by a specific wallet, with pagination.
        fn get_bounties_by_creator(
            &self,
            creator: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetBountiesByCreator, Self::Env>;
        /// Get all bounties in a given status, with pagination.
        fn get_bounties_by_status(
            &self,
            status: BountyStatus,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetBountiesByStatus, Self::Env>;
        /// Get bounty details by ID.
        fn get_bounty(&self, id: u64) -> sails_rs::client::PendingCall<io::GetBounty, Self::Env>;
        /// Get service config (admin, fee, bounty count).
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env>;
    }
    pub struct BountyBoardImpl;
    impl<E: sails_rs::client::GearEnv> BountyBoard for sails_rs::client::Service<BountyBoardImpl, E> {
        type Env = E;
        fn approve_bounty(
            &mut self,
            bounty_id: u64,
        ) -> sails_rs::client::PendingCall<io::ApproveBounty, Self::Env> {
            self.pending_call((bounty_id,))
        }
        fn cancel_bounty(
            &mut self,
            bounty_id: u64,
        ) -> sails_rs::client::PendingCall<io::CancelBounty, Self::Env> {
            self.pending_call((bounty_id,))
        }
        fn claim_bounty(
            &mut self,
            bounty_id: u64,
        ) -> sails_rs::client::PendingCall<io::ClaimBounty, Self::Env> {
            self.pending_call((bounty_id,))
        }
        fn import_state(
            &mut self,
            encoded_state: Vec<u8>,
        ) -> sails_rs::client::PendingCall<io::ImportState, Self::Env> {
            self.pending_call((encoded_state,))
        }
        fn post_bounty(
            &mut self,
            description: String,
            metadata_url: String,
        ) -> sails_rs::client::PendingCall<io::PostBounty, Self::Env> {
            self.pending_call((description, metadata_url))
        }
        fn set_fee(
            &mut self,
            new_fee: u128,
        ) -> sails_rs::client::PendingCall<io::SetFee, Self::Env> {
            self.pending_call((new_fee,))
        }
        fn submit_work(
            &mut self,
            bounty_id: u64,
            proof_url: String,
        ) -> sails_rs::client::PendingCall<io::SubmitWork, Self::Env> {
            self.pending_call((bounty_id, proof_url))
        }
        fn withdraw_fees(&mut self) -> sails_rs::client::PendingCall<io::WithdrawFees, Self::Env> {
            self.pending_call(())
        }
        fn export_state(&self) -> sails_rs::client::PendingCall<io::ExportState, Self::Env> {
            self.pending_call(())
        }
        fn get_bounties_by_creator(
            &self,
            creator: ActorId,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetBountiesByCreator, Self::Env> {
            self.pending_call((creator, cursor, limit))
        }
        fn get_bounties_by_status(
            &self,
            status: BountyStatus,
            cursor: Option<u64>,
            limit: u32,
        ) -> sails_rs::client::PendingCall<io::GetBountiesByStatus, Self::Env> {
            self.pending_call((status, cursor, limit))
        }
        fn get_bounty(&self, id: u64) -> sails_rs::client::PendingCall<io::GetBounty, Self::Env> {
            self.pending_call((id,))
        }
        fn get_config(&self) -> sails_rs::client::PendingCall<io::GetConfig, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ApproveBounty (bounty_id: u64) -> ());
        sails_rs::io_struct_impl!(CancelBounty (bounty_id: u64) -> ());
        sails_rs::io_struct_impl!(ClaimBounty (bounty_id: u64) -> ());
        sails_rs::io_struct_impl!(ImportState (encoded_state: Vec<u8>) -> ());
        sails_rs::io_struct_impl!(PostBounty (description: String, metadata_url: String) -> u64);
        sails_rs::io_struct_impl!(SetFee (new_fee: u128) -> ());
        sails_rs::io_struct_impl!(SubmitWork (bounty_id: u64, proof_url: String) -> ());
        sails_rs::io_struct_impl!(WithdrawFees () -> ());
        sails_rs::io_struct_impl!(ExportState () -> Vec<u8>);
        sails_rs::io_struct_impl!(GetBountiesByCreator (creator: ActorId, cursor: Option<u64>, limit: u32) -> super::BountyPage);
        sails_rs::io_struct_impl!(GetBountiesByStatus (status: super::BountyStatus, cursor: Option<u64>, limit: u32) -> super::BountyPage);
        sails_rs::io_struct_impl!(GetBounty (id: u64) -> Option<super::Bounty>);
        sails_rs::io_struct_impl!(GetConfig () -> super::Config);
    }

    #[cfg(not(target_arch = "wasm32"))]
    pub mod events {
        use super::*;
        #[derive(PartialEq, Debug, Encode, Decode)]
        #[codec(crate = sails_rs::scale_codec)]
        pub enum BountyBoardEvents {
            BountyPosted {
                id: u64,
                creator: ActorId,
                description: String,
                reward: u128,
                fee_paid: u128,
            },
            BountyClaimed {
                id: u64,
                claimant: ActorId,
            },
            WorkSubmitted {
                id: u64,
                proof_url: String,
            },
            BountyApproved {
                id: u64,
                reward: u128,
                creator: ActorId,
                claimant: ActorId,
            },
            BountyCancelled {
                id: u64,
                reward_returned: u128,
            },
            FeeUpdated {
                old_fee: u128,
                new_fee: u128,
            },
            FeesWithdrawn {
                amount: u128,
                to: ActorId,
            },
        }
        impl sails_rs::client::Event for BountyBoardEvents {
            const EVENT_NAMES: &'static [Route] = &[
                "BountyPosted",
                "BountyClaimed",
                "WorkSubmitted",
                "BountyApproved",
                "BountyCancelled",
                "FeeUpdated",
                "FeesWithdrawn",
            ];
        }
        impl sails_rs::client::ServiceWithEvents for BountyBoardImpl {
            type Event = BountyBoardEvents;
        }
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct BountyPage {
    pub bounties: Vec<Bounty>,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Bounty {
    pub id: u64,
    pub creator: ActorId,
    pub description: String,
    pub metadata_url: String,
    pub reward: u128,
    pub status: BountyStatus,
    pub claimant: Option<ActorId>,
    pub proof_url: Option<String>,
    pub created_at: u64,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum BountyStatus {
    Open,
    Claimed,
    Submitted,
    Approved,
    Cancelled,
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub struct Config {
    pub admin: ActorId,
    pub fee: u128,
    pub bounty_count: u64,
}
